[package]
name = "balp_tennis_kata"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A Library implementing the Tennis game kata"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
